Repository KrayonDigital/krayon-ts-sdk, pull requests merged in 2023-08, with the labels that each got.

#10 fix(KD-1207) add ?
  packages/core-sdk/src/lib/types/wallet.ts
Labels: bug, enhancement

#11 KD-1318 - add aggregated_usd_balance
  packages/core-sdk/package.json
  packages/core-sdk/src/lib/types/wallet.ts
Labels: bug, enhancement

#12 KD-1260 : user-interface
  packages/core-sdk/package.json
  packages/core-sdk/src/lib/types/user.ts
Labels: bug

#13 KD-1335-fix transfer response
  packages/core-sdk/package.json
  packages/core-sdk/src/lib/transfer/transfer-sdk.ts
Labels: bug

#14 KD-1339-fix approvers number
  .github/pull_request_template.md
  packages/core-sdk/package.json
  packages/core-sdk/src/lib/types/wallet.ts
Labels: bug, chore

#17 KD-1356/fix fe login issue
  packages/core-sdk/package.json
  packages/core-sdk/project.json
  packages/core-sdk/src/LICENSE
  packages/core-sdk/src/README.md
  packages/core-sdk/src/lib/main.ts
  packages/react-auth0-sdk/package.json
  packages/react-auth0-sdk/src/LICENSE
  packages/react-auth0-sdk/src/README.md
  packages/react-auth0-sdk/src/auth0-sdk-provider.tsx
  packages/react-auth0-sdk/src/components/walletconnect/AvailableWalletsProvider.tsx
  packages/walletconnect-sdk/package.json
  packages/walletconnect-sdk/project.json
  packages/walletconnect-sdk/src/LICENSE
  packages/walletconnect-sdk/src/README.md
Labels: bug, chore

#19 KD-1350/gas station incorrect transfer screen
  packages/core-sdk/package.json
  packages/core-sdk/src/lib/gas-station/gas-station-sdk.ts
  packages/core-sdk/src/lib/types/gas-station.ts
Labels: bug

#24 KD-1390 fix related pr
  packages/core-sdk/package.json
  packages/core-sdk/src/lib/types/election.ts
Labels: bug

#20 KD-1367/dynamic-after-assigning-unassigning-wallets-to-user
  packages/core-sdk/package.json
  packages/core-sdk/src/lib/types/user.ts
  packages/core-sdk/src/lib/user/user-sdk.ts
Labels: bug
