Repository KrayonDigital/krayon-ts-sdk, pull requests merged in 2023-12, with the labels that each got.

#65 KD-1676 - settlement-fixes
  packages/core-sdk/src/lib/types/deposit.ts
Labels: bug

#66 KD-0001/fix deposits balance endpoint
  packages/core-sdk/src/lib/deposit/deposit-sdk.ts
  packages/core-sdk/src/lib/types/deposit.ts
Labels: bug, hotfix

#67 KD-1680 - add-settlements-view
  packages/core-sdk/src/lib/deposit/deposit-sdk.ts
  packages/core-sdk/src/lib/settlement/settlement-sdk.ts
  packages/core-sdk/src/lib/types/index.ts
  packages/core-sdk/src/lib/types/settelments.ts
Labels: enhancement

#68 KD-1689/change the DTOs and api endpoint calll
  packages/core-sdk/src/lib/types/util.ts
  packages/core-sdk/src/lib/util/util-sdk.ts
Labels: enhancement

#69 KD-1687 - add-pagination
  packages/core-sdk/src/index.ts
  packages/core-sdk/src/lib/types/common.ts
  packages/core-sdk/src/lib/types/election.ts
  packages/core-sdk/src/lib/types/label.ts
  packages/core-sdk/src/lib/wallet/wallet-sdk.ts
Labels: enhancement

#70 Feat/kd 1695/transfer notifications filter tab
  packages/core-sdk/src/lib/notification/notification-sdk.ts
  packages/core-sdk/src/lib/types/notification.ts
Labels: enhancement

#71 KD-1695 - fixes
  packages/core-sdk/src/lib/types/label.ts
Labels: bug

#47 KD-1579 withdrawl
  packages/core-sdk/src/lib/organization/organization-sdk.ts
  packages/core-sdk/src/lib/transfer/transfer-sdk.ts
  packages/core-sdk/src/lib/types/transfer.ts
Labels: enhancement

#73 KD-1728 - settlement_fee
  packages/core-sdk/src/lib/types/settelments.ts
Labels: bug, enhancement

#74 KD-0000/wip
  packages/core-sdk/src/lib/types/settelments.ts
Labels: bug

#75 KD-1753 - impl deposit/settlements to csv
  packages/core-sdk/src/lib/deposit/deposit-sdk.ts
  packages/core-sdk/src/lib/settlement/settlement-sdk.ts
Labels: enhancement
