Repository KrayonDigital/krayon-ts-sdk, pull requests merged in 2024-05, with the labels that each got.

#109 Feat/kd 1955/sweep stop
  packages/core-sdk/src/lib/types/settelments.ts
  packages/core-sdk/src/lib/wallet/wallet-sdk.ts
Labels: enhancement

#110 KD-0000/add reference to the payment details
  packages/core-sdk/src/lib/types/checkout.ts
Labels: enhancement

#111 KD-1978 - checkout-UPI-SAP
  packages/core-sdk/src/lib/checkout/checkout-sdk.ts
  packages/core-sdk/src/lib/types/deposit.ts
Labels: enhancement

#112 KD-1978 - checkout-MOBILE_MONEY
  packages/core-sdk/src/lib/types/deposit.ts
Labels: bug

#113 KD-0000 - ver update on core
  packages/core-sdk/package.json
Labels: enhancement

#114 KD-1979 - more-checkout-fixes
  packages/core-sdk/src/lib/checkout/checkout-sdk.ts
  packages/core-sdk/src/lib/types/checkout.ts
Labels: bug

#115 KD-1990 - checkout-modal-fixes
  packages/core-sdk/src/lib/types/deposit.ts
Labels: bug

#116 KD-000 - checkouts/add-destination_vpa
  packages/core-sdk/src/lib/types/checkout.ts
Labels: bug, enhancement
