Repository KrayonDigital/krayon-ts-sdk, pull requests merged in 2024-04, with the labels that each got.

#101 payment details upd
  packages/core-sdk/src/lib/types/checkout.ts
Labels: enhancement

#105 KD-000 - fix-download-csv-filter
  packages/core-sdk/src/lib/deposit/deposit-sdk.ts
  packages/core-sdk/src/lib/settlement/settlement-sdk.ts
  packages/core-sdk/src/lib/transfer/transfer-sdk.ts
Labels: bug

#104 download files as blobs
  packages/core-sdk/src/lib/deposit/deposit-sdk.ts
  packages/core-sdk/src/lib/settlement/settlement-sdk.ts
  packages/core-sdk/src/lib/transfer/transfer-sdk.ts
Labels: bug, enhancement

#99 KD-1838 - mobile-views
  packages/core-sdk/src/lib/types/transfer.ts
Labels: bug

#107 ref id on transfers
  packages/core-sdk/src/lib/types/transfer.ts
Labels: enhancement
